name: Windows VPS with Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Chrome Remote Desktop Installer
        run: |
          Invoke-WebRequest https://dl.google.com/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile chromeremotedesktophost.msi

      - name: Install Chrome Remote Desktop
        run: |
          Start-Process msiexec -Wait -ArgumentList '/i chromeremotedesktophost.msi /quiet'

      - name: Set up Chrome Remote Desktop
        run: |
          # Authenticate with Google
          $credFilePath = "$env:USERPROFILE\remote-desktop-credentials.json"
          $credContents = @"
          {
            "clientId": "${{ secrets.CHROME_REMOTE_DESKTOP_CLIENT_ID }}",
            "clientSecret": "${{ secrets.CHROME_REMOTE_DESKTOP_CLIENT_SECRET }}",
            "refreshToken": "${{ secrets.CHROME_REMOTE_DESKTOP_REFRESH_TOKEN }}"
          }
          "@
          Set-Content -Path $credFilePath -Value $credContents

          # Configure Chrome Remote Desktop
          chrome-remote-desktop --headless --no-chromeos-login --pre-launch --start

      - name: Enable Remote Desktop
        run: chrome-remote-desktop --start

      - name: Set Chrome Remote Desktop PIN
        run: |
          # Set the PIN for the remote session
          $pin = "1234"
          chrome-remote-desktop --set-pin=$pin

      - name: Run loop
        run: ping -t localhost
