name: WindowsVps

on:
  push:
    branches:
      - main

jobs:
  deploy_vps:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chrome Remote Desktop
      run: |
        $url = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        $output = "chrome_remote_desktop.msi"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList '/quiet' -Wait

    - name: login chrome
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AfJohXn76YyMQNV3oj_UmYru_6oiSGmlT_xolmMdcl9fSLVbmdz7kAssuDELVyrm6gWuZQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME

    - name: Set Chrome Remote Desktop PIN
      run: |
        $pin = "1234"
        $cmd = "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        Start-Process -FilePath $cmd -ArgumentList "--pin=$pin" -Wait
