name: Windows VPS 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: downloads playit
        shell: powershell
        run: |
         Invoke-WebRequest https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3-signed.exe -OutFile playit.exe

      - name: Run Ngrok
        shell: powershell
        run: |
          .\playit.exe
          Start-Process Powershell -ArgumentList '-Noexit -Command ".\playit.exe"'
          

      - name: Activate RDP access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
   
      - name: Run loop
        run: ping -t localhost
