name: Windows VPS with RDP using Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: install plsyit
        shell: powershell
        run: |
         $downloadUrl = "https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3-signed.exe"
         $outputPath = "C:/playit.exe"
         Invoke-WebRequest -Uri $downloadUrl -OutFile $outputPath
         Start-Process -FilePath $outputPath -ArgumentList "/S" -Wait

      - name: Activate RDP access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
      - name: Change RDP password
        run: |
          $Username = "admin"
          $Password = ConvertTo-SecureString -String "admin" -AsPlainText -Force
          $User = New-LocalUser -Name $Username -Password $Password -FullName "New User" -Description "New user account" -NoPasswordExpiration
          Add-LocalGroupMember -Group "Administrators" -Member $User.Name
        

      - name: active playit
        run: |
          Start-Process -FilePath $C:/playit.exe
          
      - name: Run loop
        run: ping -t localhost
